
example1 :
	gcc example1.c ../WaveFunctionCollapse.c
	./a.out

example2 :
	gcc example2.c ../WaveFunctionCollapse.c
	./a.out

example3 :
	gcc example3.c ../WaveFunctionCollapse.c
	./a.out

example4 :
	gcc example4.c ../WaveFunctionCollapse.c
	./a.out

clean :
	rm a.out
